config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :users,
  path: '',
  controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  },
  path_names: {
    sign_in: 'signin',
    password: 'forgot',
    confirmation: 'confirm',
    sign_up: 'signup',
    sign_out: 'signout'
  }
  get "dashboard/show"
  get "charts/show", as: :chart

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :applicants, except: [:update, :destroy] do
    patch :change_stage, on: :member
    get :resume, action: :show, controller: 'resumes'
    resources :emails, only: %i[index new show create]
  end

  resources :email_replies, only: %i[new]
  resources :notifications, only: %i[index]

  namespace :careers do
    resources :accounts, only: %i[show] do
      resources :jobs, only: %i[index show], shallow: true do
        resources :applicants, only: %i[new create]
      end
    end
  end

  resources :users

  resources :invites, only: %i[create update]
  get 'invite', to: 'invites#new', as: 'accept_invite'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show; end
end

app/views/dashboard/_applicants_chart.html.erb
<div
  data-controller="applicants-chart"
  data-applicants-chart-categories-value="<%= categories %>"
  data-applicants-chart-series-value="<%= series %>"
  id="applicants-chart-container"
>
  <div class="flex justify-between">
    <h3 class="text-xl font-bold text-blue-700">Applicants by hiring stage</h3>
    <form>
      <fieldset class="mb-2">
        <div class="flex justify-between" data-controller="flatpickr">
          <%= text_field_tag "start_date",
                             nil,
                             class: "w-1/2 input rounded-none mr-2",
                             placeholder: "Start date",
                             value: 90.days.ago,
                             data: {
                               flatpickr_date_format: "Y-m-d",
                               action: "change->applicants-chart#update",
                               flatpickr_target: "start"
                             } %>
          <%= text_field_tag "end_date",
                             nil,
                             class: "w-1/2 input rounded-none mr-2",
                             placeholder: "End date",
                             value: Time.zone.now.to_date,
                             data: {
                               flatpickr_date_format: "Y-m-d",
                               action: "change->applicants-chart#update",
                               flatpickr_target: "end"
                             } %>
        </div>
      </fieldset>
    </form>
  </div>
  <div data-applicants-chart-target="chart"></div>
</div>

app/views/dashboard/_hiring_stages_chart.html.erb
<div
  data-controller="hiring-stages"
  data-hiring-stages-labels-value="<%= stage_labels %>"
  data-hiring-stages-series-value="<%= stage_series %>"
  id="stage-chart-container"
>
  <div class="flex justify-between">
    <h3 class="text-xl font-bold text-blue-700">Applicants by hiring stage</h3>
    <form>
      <%= select_tag "job_id",
                     options_for_select(
                       Job.for_account(current_user.account).order(:title).pluck(:title, :id)
                     ),
                     include_blank: "All jobs",
                     data: {
                       action: "change->hiring-stages#update"
                     }
      %>
    </form>
  </div>
  <div data-hiring-stages-target="chart"></div>
</div>

app/views/dashboard/show.html.erb
<div>
  <h2 class="mt-6 text-3xl font-extrabold text-gray-700">
    Recruiting Dashboard
  </h2>
</div>

<div class="flex w-full space-x-8 sm:flex-col md:flex-row flex-1">
  <div id="applicants-chart" class="sm:w-full md:w-1/2">
    <%= turbo_frame_tag "applicants_chart", src: chart_path(chart_type: "Charts::ApplicantsChart"), loading: "lazy" %>
  </div>
  <div id="hiring-stages-chart" class="sm:w-full md:w-1/2">
    <%= turbo_frame_tag "hiring_stages_chart", src: chart_path(chart_type: "Charts::HiringStagesChart"), loading: "lazy" %>
  </div>
</div>